const copy = [
	{
		startText: 'Data never sleeps. ',
		linkText: '',
		endText: '',
		link: '',
		animationType: 'sequential',
	},
	{
		startText: 'Some CEOs ',
		linkText: 'go to bed with it',
		endText: '. ',
		link: '/insights/do-you-sleep-with-your-data',
		animationType: 'whole',
	},
	{
		startText: 'Others ',
		linkText: 'leave it at the office',
		endText: '. ',
		link: '/insights/devices-set-you-free',
		animationType: 'whole',
	},
	{
		startText: "Almost every leader thinks they've ",
		linkText: 'got a good handle on it',
		endText: ". Even when they can't get hold of it at all. ",
		link: '/insights/misplaced-confidence',
		animationType: 'whole',
	},
	{
		startText: 'Most CEOs are ',
		linkText: 'living in the past',
		endText: '. ',
		link: '/insights/are-you-stuck-in-the-past',
		animationType: 'whole',
	},
	{
		startText: 'Especially the ',
		linkText: 'British',
		endText: '. ',
		link: '/insights/different-time-zones',
		animationType: 'whole',
	},
	{
		startText: 'Almost all leaders ',
		linkText: 'trust it',
		endText: '. ',
		link: '/insights/do-you-go-with-your-gut',
		animationType: 'whole',
	},
	{
		startText: 'Especially the ',
		linkText: 'middle-aged',
		endText: '. ',
		link: '/insights/acting-your-age',
		animationType: 'whole',
	},
	{
		startText: 'Yet the majority are also ',
		linkText: 'scared of it',
		endText: '. Especially the young. ',
		link: '/insights/data-shouldnt-be-scary',
		animationType: 'whole',
	},
	{
		startText: 'Attention-draining meetings ',
		linkText: 'try to explain it',
		endText: '. ',
		link: '/insights/we-cant-keep-meeting-like-this',
		animationType: 'whole',
	},
	{
		startText: 'Time-consuming reports ',
		linkText: 'analyse it',
		endText: '. ',
		link: '/insights/report-your-reporting',
		animationType: 'whole',
	},
	{
		startText: "Let's make it more ",
		linkText: 'powerful',
		endText: '. ',
		link: '/insights/do-you-want-to-be-a-hero',
		animationType: 'whole',
	},
	{
		startText: 'And ',
		linkText: 'pocket-sized',
		endText: '. ',
		link: '/insights/room-to-improve',
		animationType: 'whole',
	},
];

export default copy;
